logging:
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
    org: INFO

spring:
  application:
    name: penste
  profiles:
    active=local:
  datasource:
    url: jdbc:postgresql://localhost:5432/penste
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yml
  output:
    ansi:
      enabled: ALWAYS